# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20160127_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
